name: flutter_markdown_web
author: Flutter Authors <flutter-dev@googlegroups.com>
description: A Markdown renderer for Flutter.
homepage: https://github.com/flutter/flutter_markdown
version: 0.2.0

dependencies:
  flutter_web: any
  flutter_web_ui: any
  markdown: ^2.0.0
  meta: ^1.0.5
  string_scanner: ^1.0.0
  path: ^1.5.1

environment:
  sdk: '>=2.3.0-dev.0.1 <3.0.0'
